export const FIND_STOCK_SUMMARY_REQUEST = 'FIND_STOCK_SUMMARY_REQUEST';
export const FIND_STOCK_SUMMARY_SUCCESS = 'FIND_STOCK_SUMMARY_SUCCESS';
export const FIND_STOCK_SUMMARY_FAILURE = 'FIND_STOCK_SUMMARY_FAILURE';

export const FIND_TRANSACTION_CHART_SUMMARY_REQUEST =
  'FIND_TRANSACTION_CHART_SUMMARY_REQUEST';
export const FIND_TRANSACTION_CHART_SUMMARY_SUCCESS =
  'FIND_TRANSACTION_CHART_SUMMARY_SUCCESS';
export const FIND_TRANSACTION_CHART_SUMMARY_FAILURE =
  'FIND_TRANSACTION_CHART_SUMMARY_FAILURE';

export const FIND_ITEM_REQUEST = 'FIND_ITEM_REQUEST';
export const FIND_ITEM_SUCCESS = 'FIND_ITEM_SUCCESS';
export const FIND_ITEM_FAILURE = 'FIND_ITEM_FAILURE';

export const FIND_ITEMS_REQUEST = 'FIND_ITEMS_REQUEST';
export const FIND_ITEMS_SUCCESS = 'FIND_ITEMS_SUCCESS';
export const FIND_ITEMS_FAILURE = 'FIND_ITEMS_FAILURE';

export const FIND_ITEMS_SEARCH_REQUEST = 'FIND_ITEMS_SEARCH_REQUEST';
export const FIND_ITEMS_SEARCH_SUCCESS = 'FIND_ITEMS_SEARCH_SUCCESS';
export const FIND_ITEMS_SEARCH_FAILURE = 'FIND_ITEMS_SEARCH_FAILURE';

export const FIND_UNITS_SEARCH_REQUEST = 'FIND_UNITS_SEARCH_REQUEST';
export const FIND_UNITS_SEARCH_SUCCESS = 'FIND_UNITS_SEARCH_SUCCESS';
export const FIND_UNITS_SEARCH_FAILURE = 'FIND_UNITS_SEARCH_FAILURE';

export const SAVE_ITEM_REQUEST = 'SAVE_ITEM_REQUEST';
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAILURE = 'SAVE_ITEM_FAILURE';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

export const DELETE_ITEMS_REQUEST = 'DELETE_ITEMS_REQUEST';
export const DELETE_ITEMS_SUCCESS = 'DELETE_ITEMS_SUCCESS';
export const DELETE_ITEMS_FAILURE = 'DELETE_ITEMS_FAILURE';

export const FIND_UNIT_REQUEST = 'FIND_UNIT_REQUEST';
export const FIND_UNIT_SUCCESS = 'FIND_UNIT_SUCCESS';
export const FIND_UNIT_FAILURE = 'FIND_UNIT_FAILURE';

export const FIND_UNITS_REQUEST = 'FIND_UNITS_REQUEST';
export const FIND_UNITS_SUCCESS = 'FIND_UNITS_SUCCESS';
export const FIND_UNITS_FAILURE = 'FIND_UNITS_FAILURE';

export const SAVE_UNIT_REQUEST = 'SAVE_UNIT_REQUEST';
export const SAVE_UNIT_SUCCESS = 'SAVE_UNIT_SUCCESS';
export const SAVE_UNIT_FAILURE = 'SAVE_UNIT_FAILURE';

export const DELETE_UNIT_REQUEST = 'DELETE_UNIT_REQUEST';
export const DELETE_UNIT_SUCCESS = 'DELETE_UNIT_SUCCESS';
export const DELETE_UNIT_FAILURE = 'DELETE_UNIT_FAILURE';

export const DELETE_UNITS_REQUEST = 'DELETE_UNITS_REQUEST';
export const DELETE_UNITS_SUCCESS = 'DELETE_UNITS_SUCCESS';
export const DELETE_UNITS_FAILURE = 'DELETE_UNITS_FAILURE';

export const FIND_STOCK_REQUEST = 'FIND_STOCK_REQUEST';
export const FIND_STOCK_SUCCESS = 'FIND_STOCK_SUCCESS';
export const FIND_STOCK_FAILURE = 'FIND_STOCK_FAILURE';

export const FIND_STOCKS_REQUEST = 'FIND_STOCKS_REQUEST';
export const FIND_STOCKS_SUCCESS = 'FIND_STOCKS_SUCCESS';
export const FIND_STOCKS_FAILURE = 'FIND_STOCKS_FAILURE';

export const SAVE_STOCK_REQUEST = 'SAVE_STOCK_REQUEST';
export const SAVE_STOCK_SUCCESS = 'SAVE_STOCK_SUCCESS';
export const SAVE_STOCK_FAILURE = 'SAVE_STOCK_FAILURE';

export const DELETE_STOCK_REQUEST = 'DELETE_STOCK_REQUEST';
export const DELETE_STOCK_SUCCESS = 'DELETE_STOCK_SUCCESS';
export const DELETE_STOCK_FAILURE = 'DELETE_STOCK_FAILURE';

export const DELETE_STOCKS_REQUEST = 'DELETE_STOCKS_REQUEST';
export const DELETE_STOCKS_SUCCESS = 'DELETE_STOCKS_SUCCESS';
export const DELETE_STOCKS_FAILURE = 'DELETE_STOCKS_FAILURE';

export const FIND_TRANSACTION_REQUEST = 'FIND_TRANSACTION_REQUEST';
export const FIND_TRANSACTION_SUCCESS = 'FIND_TRANSACTION_SUCCESS';
export const FIND_TRANSACTION_FAILURE = 'FIND_TRANSACTION_FAILURE';

export const FIND_TRANSACTIONS_REQUEST = 'FIND_TRANSACTIONS_REQUEST';
export const FIND_TRANSACTIONS_SUCCESS = 'FIND_TRANSACTIONS_SUCCESS';
export const FIND_TRANSACTIONS_FAILURE = 'FIND_TRANSACTIONS_FAILURE';

export const SAVE_TRANSACTION_REQUEST = 'SAVE_TRANSACTION_REQUEST';
export const SAVE_TRANSACTION_SUCCESS = 'SAVE_TRANSACTION_SUCCESS';
export const SAVE_TRANSACTION_FAILURE = 'SAVE_TRANSACTION_FAILURE';

export const DELETE_TRANSACTION_REQUEST = 'DELETE_TRANSACTION_REQUEST';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAILURE = 'DELETE_TRANSACTION_FAILURE';

export const DELETE_TRANSACTIONS_REQUEST = 'DELETE_TRANSACTIONS_REQUEST';
export const DELETE_TRANSACTIONS_SUCCESS = 'DELETE_TRANSACTIONS_SUCCESS';
export const DELETE_TRANSACTIONS_FAILURE = 'DELETE_TRANSACTIONS_FAILURE';
